import { describe, it, expect } from "vitest";
import { translations } from "../i18n";

const requiredPaths: Array<string[]> = [
  ["apiManager", "modeApi"],
  ["apiManager", "modeAdvanced"],
  ["apiManager", "heroBadge"],
  ["apiManager", "status", "title"],
  ["apiManager", "status", "serverLabel"],
  ["apiManager", "status", "localLabel"],
  ["apiManager", "status", "serverDesc"],
  ["apiManager", "status", "localDesc"],
  ["apiManager", "status", "actionRetry"],
  ["apiManager", "status", "actionRetrying"],
  ["apiManager", "status", "actionDetails"],
  ["apiManager", "status", "actionHide"],
  ["apiManager", "status", "actionOpenDir"],
  ["apiManager", "status", "detailTitle"],
  ["apiManager", "status", "detailError"],
  ["apiManager", "status", "detailMessage"],
  ["apiManager", "status", "detailHint"],
  ["apiManager", "status", "detailUnknown"],
  ["apiManager", "statsApi"],
  ["apiManager", "statsApiHint"],
  ["apiManager", "statsPipeline"],
  ["apiManager", "statsPipelineHint"],
  ["apiManager", "statsGroup"],
  ["apiManager", "statsGroupHint"],
  ["apiManager", "presetTitle"],
  ["apiManager", "presetDesc"],
  ["apiManager", "presetToggleShow"],
  ["apiManager", "presetToggleHide"],
  ["apiManager", "presetCollapsedHint"],
  ["apiManager", "presetApplyHint"],
  ["apiManager", "presetNeedsConfig"],
  ["apiManager", "groupTitle"],
  ["apiManager", "groupDesc"],
  ["apiManager", "groupToggleShow"],
  ["apiManager", "groupToggleHide"],
  ["apiManager", "groupCollapsedHint"],
  ["apiManager", "groupCount"],
  ["apiManager", "groupEmptyList"],
  ["apiManager", "groupCustom"],
  ["apiManager", "groupEmpty"],
  ["apiManager", "formTitle"],
  ["apiManager", "formDesc"],
  ["apiManager", "formSectionMain"],
  ["apiManager", "formSectionAdvanced"],
  ["apiManager", "formFields", "nameLabel"],
  ["apiManager", "formFields", "idLabel"],
  ["apiManager", "formFields", "baseUrlLabel"],
  ["apiManager", "formFields", "apiKeyLabel"],
  ["apiManager", "formFields", "modelLabel"],
  ["apiManager", "formFields", "timeoutLabel"],
  ["apiManager", "formFields", "apiTypeLabel"],
  ["apiManager", "formFields", "groupLabel"],
  ["apiManager", "formFields", "membersLabel"],
  ["apiManager", "formFields", "headersLabel"],
  ["apiManager", "formFields", "paramsLabel"],
  ["apiManager", "formPlaceholders", "members"],
  ["apiManager", "formPlaceholders", "headers"],
  ["apiManager", "formPlaceholders", "params"],
  ["apiManager", "formHints", "group"],
  ["apiManager", "formHints", "members"],
  ["apiManager", "formHints", "headers"],
  ["apiManager", "formHints", "params"],
  ["apiManager", "apiTypeOptions", "openai"],
  ["apiManager", "apiTypeOptions", "pool"],
  ["apiManager", "apiTypeHints", "openai"],
  ["apiManager", "apiTypeHints", "pool"],
  ["apiManager", "formInvalidJsonTitle"],
  ["apiManager", "formInvalidJsonDesc"],
  ["apiManager", "testConnection"],
  ["apiManager", "testConnectionRunning"],
  ["apiManager", "testConnectionOk"],
  ["apiManager", "testConnectionFail"],
  ["apiManager", "testConnectionFailFallback"],
  ["apiManager", "testConnectionTimeout"],
  ["apiManager", "testConnectionHint"],
  ["apiManager", "testConnectionPoolHint"],
  ["apiManager", "templates", "title"],
  ["apiManager", "templates", "desc"],
  ["apiManager", "templates", "badge"],
  ["apiManager", "templates", "apply"],
  ["apiManager", "templates", "empty"],
  ["apiManager", "templateItems", "api_openai_basic", "title"],
  ["apiManager", "templateItems", "api_openai_basic", "desc"],
  ["apiManager", "templateItems", "api_pool_basic", "title"],
  ["apiManager", "templateItems", "api_pool_basic", "desc"],
  ["apiManager", "templateItems", "pipeline_line_strict", "title"],
  ["apiManager", "templateItems", "pipeline_line_strict", "desc"],
  ["apiManager", "templateItems", "prompt_tagged_line", "title"],
  ["apiManager", "templateItems", "prompt_tagged_line", "desc"],
  ["apiManager", "templateItems", "parser_line_strict", "title"],
  ["apiManager", "templateItems", "parser_line_strict", "desc"],
  ["apiManager", "templateItems", "parser_json_object", "title"],
  ["apiManager", "templateItems", "parser_json_object", "desc"],
  ["apiManager", "templateItems", "policy_strict", "title"],
  ["apiManager", "templateItems", "policy_strict", "desc"],
  ["apiManager", "templateItems", "chunk_line_strict", "title"],
  ["apiManager", "templateItems", "chunk_line_strict", "desc"],
  ["apiManager", "previewTitle"],
  ["apiManager", "previewDesc"],
  ["apiManager", "previewEmpty"],
  ["apiManager", "previewInvalid"],
  ["apiManager", "previewEmptyValue"],
  ["apiManager", "previewFields", "type"],
  ["apiManager", "previewFields", "baseUrl"],
  ["apiManager", "previewFields", "model"],
  ["apiManager", "previewFields", "timeout"],
  ["apiManager", "previewFields", "group"],
  ["apiManager", "previewFields", "members"],
  ["apiManager", "previewFields", "headers"],
  ["apiManager", "previewFields", "params"],
  ["apiManager", "previewFields", "provider"],
  ["apiManager", "previewFields", "prompt"],
  ["apiManager", "previewFields", "parser"],
  ["apiManager", "previewFields", "linePolicy"],
  ["apiManager", "previewFields", "chunkPolicy"],
  ["apiManager", "previewFields", "applyLinePolicy"],
  ["apiManager", "previewFields", "settings"],
  ["apiManager", "previewFields", "systemTemplate"],
  ["apiManager", "previewFields", "userTemplate"],
  ["apiManager", "previewFields", "context"],
  ["apiManager", "previewFields", "parserType"],
  ["apiManager", "previewFields", "policyType"],
  ["apiManager", "previewFields", "chunkType"],
  ["apiManager", "previewFields", "options"],
  ["apiManager", "validationPanelTitle"],
  ["apiManager", "validationPanelDesc"],
  ["apiManager", "validationPanelEmpty"],
  ["apiManager", "validationPanelInvalid"],
  ["apiManager", "validationPanelOk"],
  ["apiManager", "validationPanelErrors"],
  ["apiManager", "validationPanelWarnings"],
  ["apiManager", "composer", "title"],
  ["apiManager", "composer", "desc"],
  ["apiManager", "composer", "badge"],
  ["apiManager", "composer", "mapTitle"],
  ["apiManager", "composer", "mapHint"],
  ["apiManager", "composer", "graphHint"],
  ["apiManager", "composer", "graphActions", "autoLayout"],
  ["apiManager", "composer", "graphActions", "fitView"],
  ["apiManager", "composer", "nodes", "provider"],
  ["apiManager", "composer", "nodes", "prompt"],
  ["apiManager", "composer", "nodes", "parser"],
  ["apiManager", "composer", "nodes", "linePolicy"],
  ["apiManager", "composer", "nodes", "chunkPolicy"],
  ["apiManager", "composer", "nodes", "output"],
  ["apiManager", "composer", "nodes", "outputValue"],
  ["apiManager", "composer", "nodes", "empty"],
  ["apiManager", "composer", "nodes", "skipped"],
  ["apiManager", "composer", "fields", "idLabel"],
  ["apiManager", "composer", "fields", "nameLabel"],
  ["apiManager", "composer", "fields", "providerLabel"],
  ["apiManager", "composer", "fields", "promptLabel"],
  ["apiManager", "composer", "fields", "parserLabel"],
  ["apiManager", "composer", "fields", "linePolicyLabel"],
  ["apiManager", "composer", "fields", "chunkPolicyLabel"],
  ["apiManager", "composer", "fields", "applyLinePolicyLabel"],
  ["apiManager", "composer", "fields", "temperatureLabel"],
  ["apiManager", "composer", "fields", "maxRetriesLabel"],
  ["apiManager", "composer", "placeholders", "id"],
  ["apiManager", "composer", "placeholders", "name"],
  ["apiManager", "composer", "placeholders", "provider"],
  ["apiManager", "composer", "placeholders", "prompt"],
  ["apiManager", "composer", "placeholders", "parser"],
  ["apiManager", "composer", "placeholders", "linePolicy"],
  ["apiManager", "composer", "placeholders", "chunkPolicy"],
  ["apiManager", "composer", "placeholders", "temperature"],
  ["apiManager", "composer", "placeholders", "maxRetries"],
  ["apiManager", "composer", "sync"],
  ["apiManager", "composer", "apply"],
  ["apiManager", "composer", "missing"],
  ["apiManager", "composer", "hint"],
  ["apiManager", "presets", "openai", "label"],
  ["apiManager", "groups", "openai", "title"],
  ["apiManager", "groups", "openai", "selectPlaceholder"],
  ["apiManager", "flowTitle"],
  ["apiManager", "flowAction"],
];

const getValue = (obj: any, path: string[]) =>
  path.reduce((acc, key) => (acc ? acc[key] : undefined), obj);

describe("apiManager view i18n", () => {
  it("includes required api manager view strings", () => {
    for (const lang of Object.values(translations)) {
      for (const path of requiredPaths) {
        const value = getValue(lang, path);
        expect(value).toBeTruthy();
        expect(typeof value).toBe("string");
      }
    }
  });
});
